import { generateAlbumArtwork } from "./music-data"

// Fallback music data when YouTube API is not available
export const fallbackTrendingMusic = [
  {
    id: "dQw4w9WgXcQ",
    title: "Beautiful",
    channelTitle: "Eminem",
    thumbnail: generateAlbumArtwork("Beautiful", "Eminem"),
    duration: "6:17",
    viewCount: "1000000",
    publishedAt: "2023-01-01T00:00:00Z",
    audioUrl: "/audio/sample-hiphop.mp3",
  },
  {
    id: "kJQP7kiw5Fk",
    title: "The Look",
    channelTitle: "Roxette",
    thumbnail: generateAlbumArtwork("The Look", "Roxette"),
    duration: "3:58",
    viewCount: "500000",
    publishedAt: "2023-01-02T00:00:00Z",
    audioUrl: "/audio/sample-rock.mp3",
  },
  {
    id: "HeOVbeh2yr0",
    title: "Sucker for Pain (feat. Logic, Ty Dolla $ign & X Ambassadors)",
    channelTitle: "Imagine Dragons, Wiz Khalifa, Logic, Ty Dolla $ign, Lil Wayne & X Ambassadors",
    thumbnail: generateAlbumArtwork("Sucker for Pain", "Imagine Dragons"),
    duration: "4:03",
    viewCount: "800000",
    publishedAt: "2023-01-03T00:00:00Z",
    audioUrl: "/audio/sample-pop.mp3",
  },
  {
    id: "fJ9rUzIMcZQ",
    title: "Car Yourself (Instrumental)",
    channelTitle: "Sparsh Shah",
    thumbnail: generateAlbumArtwork("Car Yourself", "Sparsh Shah"),
    duration: "3:45",
    viewCount: "200000",
    publishedAt: "2023-01-04T00:00:00Z",
    audioUrl: "/audio/sample-instrumental.mp3",
  },
]

export const fallbackMoodPlaylists = {
  "80s sing-alongs": [
    {
      id: "dQw4w9WgXcQ1",
      title: "Don't Stop Believin'",
      channelTitle: "Journey",
      thumbnail: generateAlbumArtwork("Don't Stop Believin'", "Journey"),
      duration: "4:11",
      viewCount: "2000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-80s.mp3",
    },
    {
      id: "dQw4w9WgXcQ2",
      title: "Sweet Child O' Mine",
      channelTitle: "Guns N' Roses",
      thumbnail: generateAlbumArtwork("Sweet Child O' Mine", "Guns N' Roses"),
      duration: "5:03",
      viewCount: "1500000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-rock.mp3",
    },
  ],
  "feel-good pop & rock": [
    {
      id: "dQw4w9WgXcQ3",
      title: "Shape of You",
      channelTitle: "Ed Sheeran",
      thumbnail: generateAlbumArtwork("Shape of You", "Ed Sheeran"),
      duration: "3:53",
      viewCount: "3000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-pop.mp3",
    },
    {
      id: "dQw4w9WgXcQ4",
      title: "Uptown Funk",
      channelTitle: "Mark Ronson ft. Bruno Mars",
      thumbnail: generateAlbumArtwork("Uptown Funk", "Mark Ronson ft. Bruno Mars"),
      duration: "4:30",
      viewCount: "2500000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-funk.mp3",
    },
  ],
  "happy pop hits": [
    {
      id: "dQw4w9WgXcQ5",
      title: "Happy",
      channelTitle: "Pharrell Williams",
      thumbnail: generateAlbumArtwork("Happy", "Pharrell Williams"),
      duration: "3:52",
      viewCount: "4000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-happy.mp3",
    },
    {
      id: "dQw4w9WgXcQ6",
      title: "Can't Stop the Feeling!",
      channelTitle: "Justin Timberlake",
      thumbnail: generateAlbumArtwork("Can't Stop the Feeling!", "Justin Timberlake"),
      duration: "3:56",
      viewCount: "3500000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-upbeat.mp3",
    },
  ],
  "upbeat morning songs": [
    {
      id: "morning1",
      title: "Good as Hell",
      channelTitle: "Lizzo",
      thumbnail: generateAlbumArtwork("Good as Hell", "Lizzo"),
      duration: "2:39",
      viewCount: "2000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-upbeat.mp3",
    },
    {
      id: "morning2",
      title: "Walking on Sunshine",
      channelTitle: "Katrina and the Waves",
      thumbnail: generateAlbumArtwork("Walking on Sunshine", "Katrina and the Waves"),
      duration: "3:58",
      viewCount: "1500000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-happy.mp3",
    },
  ],
}

export const fallbackSearchResults: Record<string, any[]> = {
  "upbeat morning songs": [
    {
      id: "morning1",
      title: "Good as Hell",
      channelTitle: "Lizzo",
      thumbnail: generateAlbumArtwork("Good as Hell", "Lizzo"),
      duration: "2:39",
      viewCount: "2000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-upbeat.mp3",
    },
    {
      id: "morning2",
      title: "Walking on Sunshine",
      channelTitle: "Katrina and the Waves",
      thumbnail: generateAlbumArtwork("Walking on Sunshine", "Katrina and the Waves"),
      duration: "3:58",
      viewCount: "1500000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-happy.mp3",
    },
  ],
  "energetic pop music": [
    {
      id: "energetic1",
      title: "Levitating",
      channelTitle: "Dua Lipa",
      thumbnail: generateAlbumArtwork("Levitating", "Dua Lipa"),
      duration: "3:23",
      viewCount: "3000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-pop.mp3",
    },
    {
      id: "energetic2",
      title: "Shut Up and Dance",
      channelTitle: "Walk the Moon",
      thumbnail: generateAlbumArtwork("Shut Up and Dance", "Walk the Moon"),
      duration: "3:09",
      viewCount: "2500000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-dance.mp3",
    },
  ],
  "feel good hits": [
    {
      id: "feelgood1",
      title: "Happy",
      channelTitle: "Pharrell Williams",
      thumbnail: generateAlbumArtwork("Happy", "Pharrell Williams"),
      duration: "3:52",
      viewCount: "4000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-happy.mp3",
    },
    {
      id: "feelgood2",
      title: "Count on Me",
      channelTitle: "Bruno Mars",
      thumbnail: generateAlbumArtwork("Count on Me", "Bruno Mars"),
      duration: "3:17",
      viewCount: "2800000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-feelgood.mp3",
    },
  ],
  "pop music": [
    {
      id: "pop1",
      title: "Blinding Lights",
      channelTitle: "The Weeknd",
      thumbnail: generateAlbumArtwork("Blinding Lights", "The Weeknd"),
      duration: "3:20",
      viewCount: "2500000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-pop.mp3",
    },
    {
      id: "pop2",
      title: "Watermelon Sugar",
      channelTitle: "Harry Styles",
      thumbnail: generateAlbumArtwork("Watermelon Sugar", "Harry Styles"),
      duration: "2:54",
      viewCount: "1800000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-pop2.mp3",
    },
  ],
  "rock music": [
    {
      id: "rock1",
      title: "Bohemian Rhapsody",
      channelTitle: "Queen",
      thumbnail: generateAlbumArtwork("Bohemian Rhapsody", "Queen"),
      duration: "5:55",
      viewCount: "5000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-rock.mp3",
    },
  ],
  default: [
    {
      id: "default1",
      title: "Sample Song 1",
      channelTitle: "Sample Artist",
      thumbnail: generateAlbumArtwork("Sample Song 1", "Sample Artist"),
      duration: "3:30",
      viewCount: "1000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-music.mp3",
    },
    {
      id: "default2",
      title: "Sample Song 2",
      channelTitle: "Another Artist",
      thumbnail: generateAlbumArtwork("Sample Song 2", "Another Artist"),
      duration: "4:15",
      viewCount: "800000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-music2.mp3",
    },
  ],
}
