// Fallback music data when YouTube API is not available
export const fallbackTrendingMusic = [
  {
    id: "dQw4w9WgXcQ",
    title: "Beautiful",
    channelTitle: "Eminem",
    thumbnail: "/abstract-music-album-cover.png",
    duration: "6:17",
    viewCount: "1000000",
    publishedAt: "2023-01-01T00:00:00Z",
    audioUrl: "/audio/sample-hiphop.mp3",
  },
  {
    id: "kJQP7kiw5Fk",
    title: "The Look",
    channelTitle: "Roxette",
    thumbnail: "/roxette-the-look-album-cover.png",
    duration: "3:58",
    viewCount: "500000",
    publishedAt: "2023-01-02T00:00:00Z",
    audioUrl: "/audio/sample-rock.mp3",
  },
  {
    id: "HeOVbeh2yr0",
    title: "Sucker for Pain (feat. Logic, Ty Dolla $ign & X Ambassadors)",
    channelTitle: "Imagine Dragons, Wiz Khalifa, Logic, Ty Dolla $ign, Lil Wayne & X Ambassadors",
    thumbnail: "/suicide-squad-soundtrack-album-cover.png",
    duration: "4:03",
    viewCount: "800000",
    publishedAt: "2023-01-03T00:00:00Z",
    audioUrl: "/audio/sample-pop.mp3",
  },
  {
    id: "fJ9rUzIMcZQ",
    title: "Car Yourself (Instrumental)",
    channelTitle: "Sparsh Shah",
    thumbnail: "/sparsh-shah-album-cover.png",
    duration: "3:45",
    viewCount: "200000",
    publishedAt: "2023-01-04T00:00:00Z",
    audioUrl: "/audio/sample-instrumental.mp3",
  },
]

export const fallbackMoodPlaylists = {
  "80s sing-alongs": [
    {
      id: "dQw4w9WgXcQ1",
      title: "Don't Stop Believin'",
      channelTitle: "Journey",
      thumbnail: "/dont-stop-believin.png",
      duration: "4:11",
      viewCount: "2000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-80s.mp3",
    },
    {
      id: "dQw4w9WgXcQ2",
      title: "Sweet Child O' Mine",
      channelTitle: "Guns N' Roses",
      thumbnail: "/sweet-child-o-mine.png",
      duration: "5:03",
      viewCount: "1500000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-rock.mp3",
    },
  ],
  "feel-good pop & rock": [
    {
      id: "dQw4w9WgXcQ3",
      title: "Shape of You",
      channelTitle: "Ed Sheeran",
      thumbnail: "/ed-sheeran-portrait.png",
      duration: "3:53",
      viewCount: "3000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-pop.mp3",
    },
    {
      id: "dQw4w9WgXcQ4",
      title: "Uptown Funk",
      channelTitle: "Mark Ronson ft. Bruno Mars",
      thumbnail: "/generic-funk-album-cover.png",
      duration: "4:30",
      viewCount: "2500000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-funk.mp3",
    },
  ],
  "happy pop hits": [
    {
      id: "dQw4w9WgXcQ5",
      title: "Happy",
      channelTitle: "Pharrell Williams",
      thumbnail: "/pharrell-williams-happy.png",
      duration: "3:52",
      viewCount: "4000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-happy.mp3",
    },
    {
      id: "dQw4w9WgXcQ6",
      title: "Can't Stop the Feeling!",
      channelTitle: "Justin Timberlake",
      thumbnail: "/joyful-dancing-crowd.png",
      duration: "3:56",
      viewCount: "3500000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-upbeat.mp3",
    },
  ],
}

export const fallbackSearchResults: Record<string, any[]> = {
  "pop music": [
    {
      id: "pop1",
      title: "Blinding Lights",
      channelTitle: "The Weeknd",
      thumbnail: "/generic-synthwave-album-cover.png",
      duration: "3:20",
      viewCount: "2500000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-pop.mp3",
    },
    {
      id: "pop2",
      title: "Watermelon Sugar",
      channelTitle: "Harry Styles",
      thumbnail: "/watermelon-sugar-album-cover.png",
      duration: "2:54",
      viewCount: "1800000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-pop2.mp3",
    },
  ],
  "rock music": [
    {
      id: "rock1",
      title: "Bohemian Rhapsody",
      channelTitle: "Queen",
      thumbnail: "/bohemian-rhapsody-album-cover.png",
      duration: "5:55",
      viewCount: "5000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-rock.mp3",
    },
  ],
  default: [
    {
      id: "default1",
      title: "Sample Song 1",
      channelTitle: "Sample Artist",
      thumbnail: "/abstract-soundscape.png",
      duration: "3:30",
      viewCount: "1000000",
      publishedAt: "2023-01-01T00:00:00Z",
      audioUrl: "/audio/sample-music.mp3",
    },
    {
      id: "default2",
      title: "Sample Song 2",
      channelTitle: "Another Artist",
      thumbnail: "/music-album-cover-2.png",
      duration: "4:15",
      viewCount: "800000",
      publishedAt: "2023-01-02T00:00:00Z",
      audioUrl: "/audio/sample-music2.mp3",
    },
  ],
}
