# .github/workflows/fix-vercel-build.yml
name: Fix Vercel build

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove legacy Vercel config and extra lockfiles
        run: |
          rm -f vercel.json yarn.lock pnpm-lock.yaml
          printf "20\n" > .nvmrc

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Normalize package.json scripts and engines
        run: |
          node -e '
          const fs=require("fs"); const f="package.json";
          const pkg=JSON.parse(fs.readFileSync(f,"utf8"));
          pkg.scripts={dev:"next dev",build:"next build",start:"next start",lint:"next lint"};
          pkg.engines={node:"20.x"};
          fs.writeFileSync(f,JSON.stringify(pkg,null,2)+"\n");
          '

      - name: Clean install and optional build check
        run: |
          rm -rf node_modules .next
          npm ci
          npm run build || echo "Build failed locally (likely missing env). Proceeding to PR."

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: fix/vercel-build
          title: "Fix Vercel build for VibeTune"
          commit-message: "fix(vercel): remove legacy config, pin Node 20, standardize Next.js build"
          body: |
            - Remove legacy `vercel.json` that forced deprecated `builds` behavior.
            - Pin Node to 20.x via `engines` and `.nvmrc`.
            - Normalize Next.js scripts: dev/build/start/lint.
            - Enforce single lockfile and `npm ci`.
            - Optional local build check included in CI.
          labels: bug, vercel
          signoff: false
